
CREATE TABLE CATEGORIAS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255),
  descripcion VARCHAR(1000)
);
INSERT INTO `categorias` (`nombre`, `descripcion`) VALUES 
('Mantenimiento básico', 'El mantenimiento básico se refiere a los servicios necesarios para mantener el buen funcionamiento y prolongar la vida útil del vehículo. Incluye actividades como el cambio regular de aceite y filtros, la alineación y balanceo de las ruedas, el cambio de llantas desgastadas, el reemplazo de la batería y el ajuste de las correas y bandas. Estos servicios son fundamentales para asegurar un rendimiento óptimo del vehículo y prevenir problemas futuros.'),
('Servicios de reparación', 'Los servicios de reparación se enfocan en solucionar problemas y fallas específicas que pueden presentarse en diferentes sistemas del vehículo. Esto incluye la reparación de frenos, que abarca el diagnóstico y arreglo de cualquier fallo en el sistema de frenado para garantizar la seguridad del vehículo. También se incluye la reparación de suspensión, que se encarga de solucionar problemas en el sistema de suspensión del vehículo, como amortiguadores desgastados o componentes dañados. Además, se ofrecen servicios de reparación de transmisión, motor y sistema de escape, que se ocupan de corregir cualquier falla o mal funcionamiento en estos componentes clave del vehículo. Estos servicios de reparación requieren habilidades técnicas avanzadas y herramientas especializadas para llevar a cabo las reparaciones de manera efectiva y segura.'),
('Servicios especializado3', 'Los servicios especializados se centran en áreas específicas del vehículo que requieren conocimientos técnicos y experiencia especializada. Esto incluye el servicio de aire acondicionado, que abarca la revisión y reparación del sistema de climatización del vehículo. También se incluye el servicio de afinación, que implica ajustar y optimizar el funcionamiento del motor para mejorar el rendimiento y la eficiencia. Estos servicios requieren equipos y habilidades especiales para brindar un servicio de calidad en áreas específicas del vehículo.');
